# This is a basic workflow to help you get started with Actions

name: Ragu
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install yarn
    - run: yarn --cwd ragu-server
      env:
        CI: true
    - run: yarn --cwd ragu-dom
      env:
        CI: true
    - run: yarn --cwd ragu-vue-server-adapter
      env:
        CI: true
    - run: yarn install
      env:
        CI: true
    - run: yarn test
      env:
        CI: true
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generating Docs
      run: |
        yarn --cwd ragu-server docs
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: ragu-server/docs # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
